manipulator:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.01
  kinematics_solver_timeout: 0.5
  goal_joint_tolerance: 0.2
  goal_position_tolerance: 0.2
  goal_orientation_tolerance: 0.2
  position_only_ik: True