arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint1, joint2, joint3, joint4, joint5]
  gains:
    joint1:
      p: 1000.0
      i: 0.0
      d: 0.0
    joint2:
      p: 1000.0
      i: 0.0
      d: 0.0
    joint3:
      p: 1000.0
      i: 0.0
      d: 0.0
    joint4:
      p: 1000.0
      i: 0.0
      d: 0.0
    joint5:
      p: 1000
      i: 0.0
      d: 0.0
  constraints:
    goal_time: 5.0
    # vel_tolerance is 0 for due to the movegroup/follow_joint_trajectory/goal tolerance is empty
    stopped_velocity_tolerance: 0
    joint1: { trajectory: 0.5, goal: 0.0 }
    joint2: { trajectory: 0.5, goal: 0.0 }
    joint3: { trajectory: 0.5, goal: 0.0 }
    joint4: { trajectory: 0.5, goal: 0.0 }
    joint5: { trajectory: 0.5, goal: 0.0 }
